FROM golang:1.21.5
ARG version
COPY go.* /go/src/github.com/flowerinthenight/golang-monorepo/
COPY pkg/ /go/src/github.com/flowerinthenight/golang-monorepo/pkg/
COPY vendor/ /go/src/github.com/flowerinthenight/golang-monorepo/vendor/
COPY services/samplesvc/ /go/src/github.com/flowerinthenight/golang-monorepo/services/samplesvc/
WORKDIR /go/src/github.com/flowerinthenight/golang-monorepo/services/samplesvc/
RUN echo "HOME=$HOME"
RUN GO111MODULE=on GOFLAGS=-mod=vendor CGO_ENABLED=0 GOOS=linux go build -v -ldflags "-X github.com/flowerinthenight/golang-monorepo/services/samplesvc/main.version=$version" -a -installsuffix cgo -o samplesvc .

FROM debian:stable-slim
RUN set -x && apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*
WORKDIR /samplesvc/
COPY --from=0 /go/src/github.com/flowerinthenight/golang-monorepo/services/samplesvc .
ENTRYPOINT ["/samplesvc/samplesvc"]
CMD ["run", "--logtostderr"]
